# Copyright (c) 2026 agent-coherence contributors.
# The Coherence Protocol for AI Agents

"""Thin runner shim — the conformance corpus now ships INSIDE the package.

The corpus relocated to :mod:`ccs.testing.substrate_conformance` (WV plan
Unit 9 / R11) so a foreign implementation can import it without vendoring this
repository's test tree. This shim keeps the in-repo runner's import path
stable and holds ZERO logic of its own: every name below is the packaged
object re-exported by identity. The import direction is one-way by design —
the test tree imports the packaged corpus, never vice versa.
"""

from __future__ import annotations

from ccs.testing.substrate_conformance import (
    FSYNC_GRADE_EXEMPTION_REASON,
    MANAGED_KILL_RUN_EXEMPTION_REASON,
    WORKSPACE_BINDING_MEMBERS,
    AcknowledgedWriteLost,
    ConformanceBinding,
    ConformanceSubstrate,
    CoordinatorHarness,
    CrossProcessLostUpdate,
    InMemoryBinding,
    InMemoryStore,
    LocalWorkspaceBinding,
    LwwSubstrate,
    RestoredMemberFacts,
    SessionFactory,
    SplitComparandSubstrate,
    TornCutBlindWorkspaceBinding,
    UndeclaredDurabilityRegime,
    WorkspaceCheckpointFacts,
    WorkspaceConformanceBinding,
    WorkspaceMemberFacts,
    WorkspaceRestoreFacts,
    assert_abort_after_partial_visibility,
    assert_coordinator_retention_empty,
    assert_cross_process_one_winner_native_cas,
    assert_cross_process_rejects_read_then_write,
    assert_detect_only_silent_lost_update,
    assert_durability_regime_is_declared,
    assert_forward_only_honest,
    assert_in_process_binding_exemption_is_declared,
    assert_invalidation_before_act,
    assert_native_cas_descriptor,
    assert_never_ship_a_store_wire,
    assert_process_crash_durability,
    assert_racing_writers_one_winner,
    assert_read_pair_is_atomic,
    assert_read_pair_split_binding_is_rejected,
    assert_rejects_split_comparand,
    assert_split_view_is_rejected,
    assert_sqlite_acknowledged_commit_survives_kill,
    assert_torn_cut_blind_binding_is_rejected,
    assert_workspace_binding_declares_all,
    assert_wv_absent_is_a_fact,
    assert_wv_declared_pin_honest,
    assert_wv_declared_versioning_honest,
    assert_wv_monotonic_restore,
    assert_wv_restart_survival_per_declaration,
    assert_wv_restore_one_winner,
    assert_wv_restore_terminates_under_contention,
    assert_wv_torn_cut_detection,
    declare_deferred_durability_exemptions,
    run_native_cas_conformance,
    run_workspace_conformance,
    workspace_protocol_members,
)

__all__ = [
    "AcknowledgedWriteLost",
    "FSYNC_GRADE_EXEMPTION_REASON",
    "MANAGED_KILL_RUN_EXEMPTION_REASON",
    "UndeclaredDurabilityRegime",
    "assert_durability_regime_is_declared",
    "assert_process_crash_durability",
    "assert_sqlite_acknowledged_commit_survives_kill",
    "declare_deferred_durability_exemptions",
    "WORKSPACE_BINDING_MEMBERS",
    "ConformanceBinding",
    "ConformanceSubstrate",
    "CoordinatorHarness",
    "CrossProcessLostUpdate",
    "InMemoryBinding",
    "InMemoryStore",
    "LocalWorkspaceBinding",
    "LwwSubstrate",
    "RestoredMemberFacts",
    "SessionFactory",
    "SplitComparandSubstrate",
    "TornCutBlindWorkspaceBinding",
    "WorkspaceCheckpointFacts",
    "WorkspaceConformanceBinding",
    "WorkspaceMemberFacts",
    "WorkspaceRestoreFacts",
    "assert_abort_after_partial_visibility",
    "assert_coordinator_retention_empty",
    "assert_detect_only_silent_lost_update",
    "assert_cross_process_one_winner_native_cas",
    "assert_cross_process_rejects_read_then_write",
    "assert_forward_only_honest",
    "assert_in_process_binding_exemption_is_declared",
    "assert_invalidation_before_act",
    "assert_native_cas_descriptor",
    "assert_never_ship_a_store_wire",
    "assert_racing_writers_one_winner",
    "assert_read_pair_is_atomic",
    "assert_read_pair_split_binding_is_rejected",
    "assert_rejects_split_comparand",
    "assert_split_view_is_rejected",
    "assert_torn_cut_blind_binding_is_rejected",
    "assert_workspace_binding_declares_all",
    "assert_wv_absent_is_a_fact",
    "assert_wv_declared_pin_honest",
    "assert_wv_declared_versioning_honest",
    "assert_wv_monotonic_restore",
    "assert_wv_restart_survival_per_declaration",
    "assert_wv_restore_one_winner",
    "assert_wv_restore_terminates_under_contention",
    "assert_wv_torn_cut_detection",
    "run_native_cas_conformance",
    "run_workspace_conformance",
    "workspace_protocol_members",
]
