--------------------------- MODULE EffectGate ---------------------------
(* Effect-ordering gate amendment: the builder-facing wrapper
   (src/ccs/adapters/effect_gate.py, `gate()`) modeled over the fence world.

   `gate()` captures an input's (version, owner_generation) pair at decision
   time, re-validates the pair at the effect boundary, and fires the escaping
   effect only if BOTH are unchanged; else it HOLDs. The two comparands answer
   different questions: the version answers "is the value still the one the
   decision saw", the generation answers "is the grant it was read under still
   standing" -- a sweep reclamation advances the generation WITHOUT a version
   move (Fencing.tla's entire premise), which a version-only comparand cannot
   see. This spec proves the wrapper-level analog of NoStaleApply:

     NoStaleAdmit -- the gate never ADMITS an effect whose captured
     (version, generation) pair had moved as of the re-validate read.

   HONESTY: the ADMIT and the FIRE are TWO actions on purpose. The
   implementation's re-validate -> fire window is unclosable for an escaping
   effect (the effect escapes; the gate fires pre-effect and never rolls
   back), and every shipped doc scopes the guarantee to the re-validate point.
   Collapsing admit+fire into one atomic action would prove the stronger claim
   the docs deliberately refuse. Here the window is model-VISIBLE: a
   FencingSweepAction (or any commit) can interleave between "admitted" and
   "fired", the effect still fires, and NoStaleAdmit still holds -- because
   the invariant claims nothing about the fire instant. TLC thereby exhibits
   the disclaimed residual window rather than hiding it.

   TWO STATE-SPACE ABSTRACTIONS, both exact (no lost behavior):

   1. MOVED-SINCE-CAPTURE, not concrete captured values. Both comparands are
      values of MONOTONIC counters (MonotonicVersion is an inherited checked
      invariant; ownerGeneration only ever increments, FencingSweepAction), so
      "current equals captured" is EXACTLY "unchanged since capture" -- no ABA
      is possible. The model therefore tracks a per-artifact boolean
      `pairMoved` (did version or ownerGeneration move since the decide
      capture?) instead of the concrete pair, sparing TLC the concrete value
      space (which made the naive encoding diverge: >80M distinct states).
      The decide capture is one atomic read in the implementation too -- the
      registry's `get_version_and_generation` returns the pair from one
      SQLite row under one lock (durable arm) / a seqlock on the monotonic
      generation (in-memory arm) -- so a torn capture needs no modeling.

   2. ONE GATE MACHINE PER ARTIFACT, not per agent. The wrapper's admit
      comparison consults ONLY per-artifact registry state (the pair); the
      caller's identity and MESI state never enter the check. Every base-
      protocol interleaving that could perturb the pair (peer commits, sweep
      reclaims of ANY holder's grant) is already generated by the base
      agents' own actions, so N gate machines add breadth without adding any
      distinguishable hazard.

   MUTANT RECIPE (what gives NoStaleAdmit teeth): delete the `~pairMoved[art]`
   guard conjunct from EffectAdmitAction. A moved pair then admits and the
   sticky flag flips -> TLC reports the NoStaleAdmit violation. Same teeth
   pattern as Fencing's NoStaleApply.

   DELIBERATELY OUT OF THIS SPEC (tested, not modeled): the fail-closed
   UNCONFIRMED comparands -- version 0 (degraded / older coordinator) and
   generation None (strict deny / a coordinator predating generation reporting) make gate() HOLD
   without consulting the pair at all; those are client-side sentinel checks
   pinned by tests/adapters/test_effect_gate_wrapper.py. The multi-artifact
   coordinator-side effect gate (a coherent cut) is Snapshot.tla's
   NoReadSkewWithinCut, not this single-artifact wrapper. *)

EXTENDS Fencing

VARIABLES effectPhase, pairMoved, staleAdmit

effectVars == <<effectPhase, pairMoved, staleAdmit>>
egVars == <<fenceVars, effectPhase, pairMoved, staleAdmit>>

(* "held" and "fired" are terminal: safety only, per the repo's safety-only
   TLC convention; a re-decide loop adds paths without adding hazards. *)
EffectPhases == {"idle", "decided", "admitted", "fired", "held"}

--------------------------------------------------------------------
(* Initialization *)
--------------------------------------------------------------------

EffectGateInit ==
    /\ FencingInit
    /\ effectPhase = [art \in Artifacts |-> "idle"]
    /\ pairMoved = [art \in Artifacts |-> FALSE]
    /\ staleAdmit = FALSE

--------------------------------------------------------------------
(* EffectDecideAction: the decision-time capture -- one atomic read of the
   (version, ownerGeneration) pair; from here `pairMoved` tracks whether any
   base step moved either component. The caller's decide() runs off-model. *)
--------------------------------------------------------------------

EffectDecideAction ==
    \E art \in Artifacts :
        /\ effectPhase[art] = "idle"
        /\ effectPhase' = [effectPhase EXCEPT ![art] = "decided"]
        /\ pairMoved' = [pairMoved EXCEPT ![art] = FALSE]
        /\ UNCHANGED <<fenceVars, staleAdmit>>

--------------------------------------------------------------------
(* EffectAdmitAction: the effect-boundary re-validate. ADMIT iff the pair is
   unchanged -- version equality alone is the pre-fix hole (a reclaim moves
   the generation without a version move; both flip `pairMoved`). The sticky
   staleAdmit flag is the mutant target (see the header recipe). *)
--------------------------------------------------------------------

EffectAdmitAction ==
    \E art \in Artifacts :
        /\ effectPhase[art] = "decided"
        /\ ~pairMoved[art]
        /\ staleAdmit' = (staleAdmit \/ pairMoved[art])
        /\ effectPhase' = [effectPhase EXCEPT ![art] = "admitted"]
        /\ pairMoved' = [pairMoved EXCEPT ![art] = FALSE]
        /\ UNCHANGED fenceVars

--------------------------------------------------------------------
(* EffectHoldAction: the HOLD (StaleView) -- the pair moved as of the
   re-validate read, so the effect never runs. Terminal here; the
   implementation's recovery (reacquire + re-decide + re-gate) is a fresh
   gate call, i.e. a fresh trace. *)
--------------------------------------------------------------------

EffectHoldAction ==
    \E art \in Artifacts :
        /\ effectPhase[art] = "decided"
        /\ pairMoved[art]
        /\ effectPhase' = [effectPhase EXCEPT ![art] = "held"]
        /\ pairMoved' = [pairMoved EXCEPT ![art] = FALSE]
        /\ UNCHANGED <<fenceVars, staleAdmit>>

--------------------------------------------------------------------
(* EffectFireAction: the escaping effect fires. DELIBERATELY unguarded --
   the admitted -> fired window is the residual re-validate -> fire window
   the docs disclaim; sweeps and commits interleave here freely and
   NoStaleAdmit still holds, because it is scoped to the re-validate point. *)
--------------------------------------------------------------------

EffectFireAction ==
    \E art \in Artifacts :
        /\ effectPhase[art] = "admitted"
        /\ effectPhase' = [effectPhase EXCEPT ![art] = "fired"]
        /\ UNCHANGED <<fenceVars, pairMoved, staleAdmit>>

--------------------------------------------------------------------
(* Specification. Base-protocol steps flip `pairMoved` for any artifact in
   the decided window whose version or ownerGeneration they move; outside
   that window the flag is canonically FALSE (reset at every phase change),
   so it never multiplies states it cannot influence. *)
--------------------------------------------------------------------

BaseStepTracksPair ==
    /\ FencingNext
    /\ pairMoved' = [art \in Artifacts |->
         IF effectPhase[art] = "decided"
         THEN pairMoved[art] \/ version'[art] /= version[art]
                             \/ ownerGeneration'[art] /= ownerGeneration[art]
         ELSE pairMoved[art]]
    /\ UNCHANGED <<effectPhase, staleAdmit>>

EffectGateNext ==
    \/ BaseStepTracksPair
    \/ EffectDecideAction
    \/ EffectAdmitAction
    \/ EffectHoldAction
    \/ EffectFireAction

EffectGateSpec == EffectGateInit /\ [][EffectGateNext]_egVars

--------------------------------------------------------------------
(* Invariants *)
--------------------------------------------------------------------

EffectGateTypeOK ==
    /\ FencingTypeOK
    /\ staleAdmit \in BOOLEAN
    /\ \A art \in Artifacts :
         /\ effectPhase[art] \in EffectPhases
         /\ pairMoved[art] \in BOOLEAN

(* Canonicalization sanity: outside the decided window the tracking flag is
   always FALSE (it is reset on every transition out of "decided" and only
   base steps inside the window set it), so it adds no spurious state. *)
PairMovedScoped ==
    \A art \in Artifacts :
        effectPhase[art] /= "decided" => pairMoved[art] = FALSE

(* The headline safety property: the gate never ADMITS an effect whose
   captured (version, generation) pair had moved as of the re-validate read.
   Scoped to the re-validate point on purpose -- the admitted -> fired window
   is the disclaimed residual (see the header); the fire instant is claimed
   nowhere, here or in the docs. *)
NoStaleAdmit == staleAdmit = FALSE

==========================================================================
